/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ObSyncPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian6 = require("obsidian");

// src/settings.ts
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  proxyUrl: "",
  // Provide a default if you host a public one
  syncFolder: "ObsidianSync",
  autoSyncInterval: 0,
  syncOnStartup: false,
  syncConfig: false,
  refreshToken: "",
  lastSyncTime: 0
};
var ObSyncSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "ObSync - Google Drive Sync Settings" });
    new import_obsidian.Setting(containerEl).setName("Authentication Proxy URL").setDesc("The URL of your Cloudflare Worker Proxy (e.g. https://your-worker.workers.dev)").addText((text) => text.setPlaceholder("https://...").setValue(this.plugin.settings.proxyUrl).onChange(async (value) => {
      this.plugin.settings.proxyUrl = value.replace(/\/$/, "");
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Authenticate with Google Drive").setDesc(this.plugin.settings.refreshToken ? "You are currently authenticated." : "Click to authenticate and grant access to Google Drive.").addButton((button) => button.setButtonText(this.plugin.settings.refreshToken ? "Re-Authenticate" : "Authenticate").setCta().onClick(() => {
      if (!this.plugin.settings.proxyUrl) {
        new import_obsidian.Notice("Please configure the Authentication Proxy URL first.");
        return;
      }
      this.plugin.googleAuth.startAuthFlow();
    }));
    if (this.plugin.settings.refreshToken) {
      new import_obsidian.Setting(containerEl).setName("Disconnect").setDesc("Remove authentication tokens from this device.").addButton((button) => button.setButtonText("Disconnect").setWarning().onClick(async () => {
        this.plugin.settings.refreshToken = "";
        await this.plugin.saveSettings();
        this.display();
      }));
    }
    new import_obsidian.Setting(containerEl).setName("Sync Folder Name").setDesc("The name of the folder in Google Drive where files will be synced.").addText((text) => text.setPlaceholder("ObsidianSync").setValue(this.plugin.settings.syncFolder).onChange(async (value) => {
      this.plugin.settings.syncFolder = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Auto-Sync Interval (minutes)").setDesc("How often to sync automatically in the background. Set to 0 to disable.").addText((text) => text.setPlaceholder("0").setValue(String(this.plugin.settings.autoSyncInterval)).onChange(async (value) => {
      const num = parseInt(value, 10);
      if (!isNaN(num)) {
        this.plugin.settings.autoSyncInterval = num;
        await this.plugin.saveSettings();
        this.plugin.setupAutoSync();
      }
    }));
    new import_obsidian.Setting(containerEl).setName("Sync on Startup").setDesc("Automatically trigger a sync when Obsidian starts.").addToggle((toggle) => toggle.setValue(this.plugin.settings.syncOnStartup).onChange(async (value) => {
      this.plugin.settings.syncOnStartup = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Sync Configuration (Plugins, Themes, Snippets)").setDesc("Sync the hidden .obsidian folder. Safely ignores workspace layouts and this plugin's auth tokens to prevent device conflicts.").addToggle((toggle) => toggle.setValue(this.plugin.settings.syncConfig).onChange(async (value) => {
      this.plugin.settings.syncConfig = value;
      await this.plugin.saveSettings();
    }));
  }
};

// src/googleAuth.ts
var import_obsidian2 = require("obsidian");
var GoogleAuth = class {
  constructor(plugin) {
    this.accessToken = null;
    this.accessTokenExpiry = 0;
    this.plugin = plugin;
  }
  startAuthFlow() {
    if (!this.plugin.settings.proxyUrl) {
      new import_obsidian2.Notice("Please provide a Proxy URL in settings first.");
      return;
    }
    const loginUrl = `${this.plugin.settings.proxyUrl}/login`;
    window.open(loginUrl);
    new import_obsidian2.Notice("Opened browser for Google Auth. Waiting for response...");
  }
  // This is called by main.ts when the obsidian://obsync-auth URI is triggered
  async handleAuthCallback(refreshToken, accessToken, expiresIn) {
    this.plugin.settings.refreshToken = refreshToken;
    this.accessToken = accessToken;
    this.accessTokenExpiry = Date.now() + expiresIn * 1e3 - 6e4;
    await this.plugin.saveSettings();
    new import_obsidian2.Notice("Successfully authenticated with Google Drive!");
  }
  async getValidAccessToken() {
    if (this.accessToken && Date.now() < this.accessTokenExpiry) {
      return this.accessToken;
    }
    if (!this.plugin.settings.refreshToken || !this.plugin.settings.proxyUrl) {
      return null;
    }
    try {
      const response = await (0, import_obsidian2.requestUrl)({
        url: `${this.plugin.settings.proxyUrl}/refresh`,
        method: "POST",
        headers: {
          "Content-Type": "application/json"
        },
        body: JSON.stringify({
          refresh_token: this.plugin.settings.refreshToken
        })
      });
      if (response.status === 200) {
        const data = response.json;
        this.accessToken = data.access_token;
        this.accessTokenExpiry = Date.now() + data.expires_in * 1e3 - 6e4;
        return this.accessToken;
      } else {
        this.plugin.settings.refreshToken = "";
        await this.plugin.saveSettings();
        new import_obsidian2.Notice("Session expired or proxy error. Please re-authenticate.");
        return null;
      }
    } catch (e) {
      console.error("Failed to refresh token via proxy", e);
      return null;
    }
  }
};

// src/googleDriveApi.ts
var import_obsidian3 = require("obsidian");
var GoogleDriveApi = class {
  // path -> folderId
  constructor(auth) {
    this.folderCache = /* @__PURE__ */ new Map();
    this.auth = auth;
  }
  async request(url, method = "GET", body, contentType, returnType = "json", retries = 3) {
    const token = await this.auth.getValidAccessToken();
    if (!token)
      throw new Error("Not authenticated");
    const headers = {
      "Authorization": `Bearer ${token}`
    };
    let requestBody = void 0;
    if (body) {
      if (contentType) {
        headers["Content-Type"] = contentType;
        requestBody = body;
      } else {
        headers["Content-Type"] = "application/json";
        requestBody = JSON.stringify(body);
      }
    }
    await new Promise((resolve) => window.setTimeout(resolve, 150));
    let attempt = 0;
    while (attempt <= retries) {
      attempt++;
      const response = await (0, import_obsidian3.requestUrl)({
        url,
        method,
        headers,
        body: requestBody,
        throw: false
        // Crucial: don't auto-throw so we can parse the real error!
      });
      if (response.status >= 200 && response.status < 300) {
        if (returnType === "arraybuffer") {
          return response.arrayBuffer;
        }
        return response.json;
      }
      if ((response.status === 403 || response.status === 429 || response.status >= 500) && attempt <= retries) {
        const backoffTime = attempt * 2e3;
        console.log(`Drive API rate limited/server error (${response.status}). Retrying in ${backoffTime}ms...`);
        await new Promise((resolve) => window.setTimeout(resolve, backoffTime));
        continue;
      }
      let errorMsg = response.text;
      try {
        const parsed = JSON.parse(response.text);
        if (parsed.error && parsed.error.message) {
          errorMsg = parsed.error.message;
        }
      } catch (e) {
      }
      throw new Error(`Drive API Error ${response.status}: ${errorMsg}`);
    }
  }
  async getFolderId(folderName, parentId) {
    let q = `mimeType='application/vnd.google-apps.folder' and name='${folderName}' and trashed=false`;
    if (parentId) {
      q += ` and '${parentId}' in parents`;
    } else {
      q += ` and 'root' in parents`;
    }
    const res = await this.request(`https://www.googleapis.com/drive/v3/files?q=${encodeURIComponent(q)}&fields=files(id,name)`);
    if (res.files && res.files.length > 0) {
      return res.files[0].id;
    }
    return null;
  }
  async createFolder(folderName, parentId) {
    const metadata = {
      name: folderName,
      mimeType: "application/vnd.google-apps.folder"
    };
    if (parentId) {
      metadata.parents = [parentId];
    }
    const res = await this.request("https://www.googleapis.com/drive/v3/files", "POST", metadata);
    return res.id;
  }
  async ensureRootFolder(folderName) {
    let folderId = await this.getFolderId(folderName);
    if (!folderId) {
      folderId = await this.createFolder(folderName);
    }
    this.folderCache.clear();
    return folderId;
  }
  async getOrCreateFolderTree(folderPath, rootFolderId) {
    if (!folderPath)
      return rootFolderId;
    if (this.folderCache.has(folderPath)) {
      return this.folderCache.get(folderPath);
    }
    const parts = folderPath.split("/");
    let currentParentId = rootFolderId;
    let currentPath = "";
    for (const part of parts) {
      currentPath += (currentPath === "" ? "" : "/") + part;
      if (this.folderCache.has(currentPath)) {
        currentParentId = this.folderCache.get(currentPath);
        continue;
      }
      let id = await this.getFolderId(part, currentParentId);
      if (!id) {
        id = await this.createFolder(part, currentParentId);
      }
      this.folderCache.set(currentPath, id);
      currentParentId = id;
    }
    return currentParentId;
  }
  async listAllVaultFiles(rootFolderId) {
    let files = [];
    let pageToken = "";
    const q = `trashed=false and appProperties has { key='syncFolderId' and value='${rootFolderId}' }`;
    do {
      const url = `https://www.googleapis.com/drive/v3/files?q=${encodeURIComponent(q)}&fields=nextPageToken,files(id,name,mimeType,modifiedTime,description)&pageSize=1000${pageToken ? `&pageToken=${pageToken}` : ""}`;
      const res = await this.request(url);
      if (res.files) {
        for (const f of res.files) {
          if (f.description) {
            files.push({
              id: f.id,
              name: f.name,
              mimeType: f.mimeType,
              modifiedTime: f.modifiedTime,
              vaultPath: f.description
            });
          }
        }
      }
      pageToken = res.nextPageToken || "";
    } while (pageToken);
    return files;
  }
  async uploadFile(targetFolderId, name, vaultPath, rootFolderId, content, existingId, modifiedTime) {
    const metadata = {
      name,
      description: vaultPath,
      appProperties: {
        syncFolderId: rootFolderId
      }
    };
    if (modifiedTime) {
      metadata.modifiedTime = modifiedTime;
    }
    if (!existingId) {
      metadata.parents = [targetFolderId];
    }
    const boundary = "-------314159265358979323846";
    const delimiter = `\r
--${boundary}\r
`;
    const close_delim = `\r
--${boundary}--`;
    const metadataPart = `Content-Type: application/json; charset=UTF-8\r
\r
${JSON.stringify(metadata)}`;
    let base64Data = "";
    const bytes = new Uint8Array(content);
    const chunk = 8192;
    for (let i = 0; i < bytes.length; i += chunk) {
      base64Data += String.fromCharCode.apply(null, Array.from(bytes.subarray(i, i + chunk)));
    }
    const base64Content = btoa(base64Data);
    const mediaPart = `Content-Type: application/octet-stream\r
Content-Transfer-Encoding: base64\r
\r
${base64Content}`;
    const multipartRequestBody = `${delimiter}${metadataPart}${delimiter}${mediaPart}${close_delim}`;
    const url = existingId ? `https://www.googleapis.com/upload/drive/v3/files/${existingId}?uploadType=multipart&fields=id,name,mimeType,modifiedTime,description` : `https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id,name,mimeType,modifiedTime,description`;
    const res = await this.request(url, existingId ? "PATCH" : "POST", multipartRequestBody, `multipart/related; boundary="${boundary}"`);
    return {
      id: res.id,
      name: res.name,
      mimeType: res.mimeType,
      modifiedTime: res.modifiedTime,
      vaultPath: res.description
    };
  }
  async downloadFile(fileId) {
    return await this.request(`https://www.googleapis.com/drive/v3/files/${fileId}?alt=media`, "GET", void 0, void 0, "arraybuffer");
  }
  async deleteFile(fileId) {
    await this.request(`https://www.googleapis.com/drive/v3/files/${fileId}`, "DELETE");
  }
};

// src/syncEngine.ts
var import_obsidian4 = require("obsidian");
var SyncEngine = class {
  constructor(plugin) {
    this.syncLock = false;
    this.statePath = ".obsidian/plugins/obsync/sync_state.json";
    this.logPath = "ObSync Log.md";
    this.activeModal = null;
    this.statusBarItem = null;
    this.progress = {
      status: "Idle",
      totalUploads: 0,
      completedUploads: 0,
      totalDownloads: 0,
      completedDownloads: 0,
      totalDeletions: 0,
      completedDeletions: 0,
      currentFile: ""
    };
    this.plugin = plugin;
  }
  updateProgressUI() {
    if (this.statusBarItem) {
      if (this.progress.status === "Idle") {
        this.statusBarItem.setText("ObSync: Up to date");
      } else if (this.progress.status === "Scanning") {
        this.statusBarItem.setText("ObSync: Scanning...");
      } else if (this.progress.status === "Syncing") {
        this.statusBarItem.setText(`ObSync: Up ${this.progress.completedUploads}/${this.progress.totalUploads} | Down ${this.progress.completedDownloads}/${this.progress.totalDownloads}`);
      } else if (this.progress.status === "Error") {
        this.statusBarItem.setText("ObSync: Error");
      }
    }
    if (this.activeModal) {
      this.activeModal.renderData();
    }
  }
  async loadState() {
    try {
      if (await this.plugin.app.vault.adapter.exists(this.statePath)) {
        const content = await this.plugin.app.vault.adapter.read(this.statePath);
        return JSON.parse(content);
      }
    } catch (e) {
      console.error("Failed to load sync state", e);
    }
    return { lastSync: 0, files: {} };
  }
  async saveState(state) {
    try {
      const dir = this.statePath.substring(0, this.statePath.lastIndexOf("/"));
      if (!await this.plugin.app.vault.adapter.exists(dir)) {
        await this.plugin.app.vault.adapter.mkdir(dir);
      }
      await this.plugin.app.vault.adapter.write(this.statePath, JSON.stringify(state, null, 2));
    } catch (e) {
      console.error("Failed to save sync state", e);
    }
  }
  async writeLog(uploads, downloads, deletions) {
    let logContent = `
## Sync: ${(/* @__PURE__ */ new Date()).toLocaleString()}
`;
    if (uploads.length === 0 && downloads.length === 0 && deletions.length === 0) {
      logContent += "- *No changes detected.*\n";
    } else {
      uploads.forEach((f) => logContent += `- **Uploaded:** \`${f}\`
`);
      downloads.forEach((f) => logContent += `- **Downloaded:** \`${f}\`
`);
      deletions.forEach((f) => logContent += `- **Deleted:** \`${f}\`
`);
    }
    try {
      if (await this.plugin.app.vault.adapter.exists(this.logPath)) {
        const existing = await this.plugin.app.vault.adapter.read(this.logPath);
        await this.plugin.app.vault.adapter.write(this.logPath, existing + logContent);
      } else {
        await this.plugin.app.vault.create(this.logPath, `# ObSync Log
${logContent}`);
      }
    } catch (e) {
      console.error("Failed to write sync log", e);
    }
  }
  async getLocalFiles() {
    const result = [];
    const adapter = this.plugin.app.vault.adapter;
    const crawl = async (folder) => {
      const listed = await adapter.list(folder);
      for (const file of listed.files) {
        if (file === this.statePath || file === this.logPath)
          continue;
        if (file.startsWith(".trash/"))
          continue;
        if (file.startsWith(".obsidian/")) {
          if (!this.plugin.settings.syncConfig)
            continue;
          if (file.includes("workspace.json") || file.includes("workspace-mobile.json") || file.startsWith(".obsidian/plugins/obsync/")) {
            continue;
          }
        }
        const stat = await adapter.stat(file);
        if (stat) {
          result.push({
            path: file,
            stat,
            name: file.includes("/") ? file.substring(file.lastIndexOf("/") + 1) : file
          });
        }
      }
      for (const subfolder of listed.folders) {
        if (subfolder.startsWith(".trash"))
          continue;
        if (subfolder.startsWith(".obsidian") && !this.plugin.settings.syncConfig)
          continue;
        if (subfolder === ".obsidian/plugins/obsync")
          continue;
        await crawl(subfolder);
      }
    };
    await crawl("");
    if (await adapter.exists(".handwriting")) {
      await crawl(".handwriting");
    }
    return result;
  }
  async runSync() {
    if (this.syncLock) {
      new import_obsidian4.Notice("Sync already in progress...");
      return;
    }
    if (!this.plugin.settings.refreshToken) {
      new import_obsidian4.Notice("Cannot sync: Not authenticated with Google Drive.");
      return;
    }
    this.syncLock = true;
    new import_obsidian4.Notice("Syncing with Google Drive...");
    this.progress = {
      status: "Scanning",
      totalUploads: 0,
      completedUploads: 0,
      totalDownloads: 0,
      completedDownloads: 0,
      totalDeletions: 0,
      completedDeletions: 0,
      currentFile: ""
    };
    this.updateProgressUI();
    const uploadedFiles = [];
    const downloadedFiles = [];
    const deletedFiles = [];
    try {
      const folderName = this.plugin.settings.syncFolder;
      const rootFolderId = await this.plugin.driveApi.ensureRootFolder(folderName);
      const driveFiles = await this.plugin.driveApi.listAllVaultFiles(rootFolderId);
      const localFiles = await this.getLocalFiles();
      const state = await this.loadState();
      const newState = { lastSync: Date.now(), files: {} };
      const driveFileMap = /* @__PURE__ */ new Map();
      for (const df of driveFiles) {
        driveFileMap.set(df.vaultPath, df);
      }
      const localFileMap = /* @__PURE__ */ new Map();
      for (const lf of localFiles) {
        localFileMap.set(lf.path, lf);
      }
      for (const [path, lFile] of localFileMap.entries()) {
        const dFile = driveFileMap.get(path);
        const lTime = lFile.stat.mtime;
        if (!dFile) {
          if (state.files[path])
            this.progress.totalDeletions++;
          else
            this.progress.totalUploads++;
        } else {
          const dTime = new Date(dFile.modifiedTime).getTime();
          if (lTime > dTime + 2e3)
            this.progress.totalUploads++;
          else if (dTime > lTime + 2e3)
            this.progress.totalDownloads++;
        }
      }
      for (const path of driveFileMap.keys()) {
        if (!localFileMap.has(path)) {
          if (state.files[path])
            this.progress.totalDeletions++;
          else
            this.progress.totalDownloads++;
        }
      }
      this.progress.status = "Syncing";
      this.updateProgressUI();
      for (const [path, lFile] of localFileMap.entries()) {
        const dFile = driveFileMap.get(path);
        const lModTime = new Date(lFile.stat.mtime).toISOString();
        const stateFileTime = state.files[path];
        const dirName = path.includes("/") ? path.substring(0, path.lastIndexOf("/")) : "";
        const fileName = lFile.name;
        if (!dFile) {
          if (stateFileTime) {
            this.progress.currentFile = path;
            this.updateProgressUI();
            await this.plugin.app.vault.adapter.remove(path);
            deletedFiles.push(path);
            this.progress.completedDeletions++;
          } else {
            this.progress.currentFile = path;
            this.updateProgressUI();
            const targetFolderId = await this.plugin.driveApi.getOrCreateFolderTree(dirName, rootFolderId);
            const content = await this.plugin.app.vault.adapter.readBinary(path);
            await this.plugin.driveApi.uploadFile(targetFolderId, fileName, path, rootFolderId, content, void 0, lModTime);
            newState.files[path] = lModTime;
            uploadedFiles.push(path);
            this.progress.completedUploads++;
          }
        } else {
          const dModTime = dFile.modifiedTime;
          const lTime = lFile.stat.mtime;
          const dTime = new Date(dModTime).getTime();
          if (lTime > dTime + 2e3) {
            this.progress.currentFile = path;
            this.updateProgressUI();
            const targetFolderId = await this.plugin.driveApi.getOrCreateFolderTree(dirName, rootFolderId);
            const content = await this.plugin.app.vault.adapter.readBinary(path);
            await this.plugin.driveApi.uploadFile(targetFolderId, fileName, path, rootFolderId, content, dFile.id, lModTime);
            newState.files[path] = lModTime;
            uploadedFiles.push(path);
            this.progress.completedUploads++;
          } else if (dTime > lTime + 2e3) {
            this.progress.currentFile = path;
            this.updateProgressUI();
            const content = await this.plugin.driveApi.downloadFile(dFile.id);
            await this.plugin.app.vault.adapter.writeBinary(path, content);
            newState.files[path] = new Date((await this.plugin.app.vault.adapter.stat(path)).mtime).toISOString();
            downloadedFiles.push(path);
            this.progress.completedDownloads++;
          } else {
            newState.files[path] = lModTime;
          }
        }
      }
      for (const [path, dFile] of driveFileMap.entries()) {
        if (!localFileMap.has(path)) {
          const stateFileTime = state.files[path];
          if (stateFileTime) {
            this.progress.currentFile = path;
            this.updateProgressUI();
            await this.plugin.driveApi.deleteFile(dFile.id);
            deletedFiles.push(path);
            this.progress.completedDeletions++;
          } else {
            this.progress.currentFile = path;
            this.updateProgressUI();
            const content = await this.plugin.driveApi.downloadFile(dFile.id);
            const parts = path.split("/");
            parts.pop();
            let currentPath = "";
            for (const part of parts) {
              currentPath += (currentPath === "" ? "" : "/") + part;
              if (!await this.plugin.app.vault.adapter.exists(currentPath)) {
                await this.plugin.app.vault.adapter.mkdir(currentPath);
              }
            }
            await this.plugin.app.vault.adapter.writeBinary(path, content);
            newState.files[path] = new Date((await this.plugin.app.vault.adapter.stat(path)).mtime).toISOString();
            downloadedFiles.push(path);
            this.progress.completedDownloads++;
          }
        }
      }
      await this.saveState(newState);
      await this.writeLog(uploadedFiles, downloadedFiles, deletedFiles);
      this.plugin.settings.lastSyncTime = Date.now();
      await this.plugin.saveSettings();
      this.progress.status = "Idle";
      this.progress.currentFile = "";
      this.updateProgressUI();
      new import_obsidian4.Notice(`Sync Complete! Up: ${uploadedFiles.length}, Down: ${downloadedFiles.length}, Del: ${deletedFiles.length}`);
    } catch (error) {
      console.error("Sync error:", error);
      this.progress.status = "Error";
      this.progress.errorMessage = error.message;
      this.updateProgressUI();
      new import_obsidian4.Notice(`Sync failed: ${error.message}`);
    } finally {
      this.syncLock = false;
    }
  }
};

// src/syncModal.ts
var import_obsidian5 = require("obsidian");
var SyncStatusModal = class extends import_obsidian5.Modal {
  constructor(app, engine) {
    super(app);
    this.engine = engine;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "ObSync Status" });
    this.contentContainer = contentEl.createDiv();
    this.renderData();
    this.engine.activeModal = this;
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
    this.engine.activeModal = null;
  }
  renderData() {
    if (!this.contentContainer)
      return;
    this.contentContainer.empty();
    const p = this.engine.progress;
    const statusEl = this.contentContainer.createEl("h3", {
      text: `Status: ${p.status}`
    });
    if (p.status === "Error" && p.errorMessage) {
      statusEl.style.color = "var(--text-error)";
      this.contentContainer.createEl("p", { text: p.errorMessage, cls: "error-message" });
    }
    if (p.status === "Scanning") {
      this.contentContainer.createEl("p", { text: "Scanning local vault and Google Drive metadata..." });
    }
    if (p.status === "Syncing" || p.status === "Idle") {
      const upDiv = this.contentContainer.createDiv({ cls: "sync-stat-row" });
      upDiv.style.marginTop = "10px";
      upDiv.createEl("strong", { text: "Uploads: " });
      upDiv.createSpan({ text: `${p.completedUploads} / ${p.totalUploads}` });
      if (p.totalUploads > 0) {
        const upProgress = upDiv.createEl("progress");
        upProgress.max = p.totalUploads;
        upProgress.value = p.completedUploads;
        upProgress.style.marginLeft = "10px";
        upProgress.style.width = "100%";
      }
      const downDiv = this.contentContainer.createDiv({ cls: "sync-stat-row" });
      downDiv.style.marginTop = "10px";
      downDiv.createEl("strong", { text: "Downloads: " });
      downDiv.createSpan({ text: `${p.completedDownloads} / ${p.totalDownloads}` });
      if (p.totalDownloads > 0) {
        const downProgress = downDiv.createEl("progress");
        downProgress.max = p.totalDownloads;
        downProgress.value = p.completedDownloads;
        downProgress.style.marginLeft = "10px";
        downProgress.style.width = "100%";
      }
      const delDiv = this.contentContainer.createDiv({ cls: "sync-stat-row" });
      delDiv.style.marginTop = "10px";
      delDiv.createEl("strong", { text: "Deletions: " });
      delDiv.createSpan({ text: `${p.completedDeletions} / ${p.totalDeletions}` });
      if (p.status === "Syncing" && p.currentFile) {
        const fileDiv = this.contentContainer.createDiv();
        fileDiv.style.marginTop = "20px";
        fileDiv.style.padding = "10px";
        fileDiv.style.backgroundColor = "var(--background-secondary)";
        fileDiv.style.borderRadius = "5px";
        fileDiv.createEl("strong", { text: "Current File: " });
        fileDiv.createEl("div", { text: p.currentFile, cls: "current-file-name" });
      }
    }
  }
};

// src/main.ts
var ObSyncPlugin = class extends import_obsidian6.Plugin {
  constructor() {
    super(...arguments);
    this.autoSyncIntervalId = null;
  }
  async onload() {
    await this.loadSettings();
    this.googleAuth = new GoogleAuth(this);
    this.driveApi = new GoogleDriveApi(this.googleAuth);
    this.syncEngine = new SyncEngine(this);
    this.statusBarItemEl = this.addStatusBarItem();
    this.statusBarItemEl.setText("ObSync: Idle");
    this.statusBarItemEl.addClass("mod-clickable");
    this.statusBarItemEl.onClickEvent(() => {
      new SyncStatusModal(this.app, this.syncEngine).open();
    });
    this.syncEngine.statusBarItem = this.statusBarItemEl;
    this.addSettingTab(new ObSyncSettingTab(this.app, this));
    this.addRibbonIcon("refresh-cw", "ObSync: Sync with Google Drive", (evt) => {
      new SyncStatusModal(this.app, this.syncEngine).open();
      this.syncEngine.runSync();
    });
    this.addCommand({
      id: "obsync-start-sync",
      name: "Start Sync",
      callback: () => {
        new SyncStatusModal(this.app, this.syncEngine).open();
        this.syncEngine.runSync();
      }
    });
    this.addCommand({
      id: "obsync-show-status",
      name: "Show Sync Progress",
      callback: () => {
        new SyncStatusModal(this.app, this.syncEngine).open();
      }
    });
    this.registerObsidianProtocolHandler("obsync-auth", async (e) => {
      if (e.refresh_token && e.access_token && e.expires_in) {
        const expiresIn = parseInt(e.expires_in, 10) || 3600;
        await this.googleAuth.handleAuthCallback(e.refresh_token, e.access_token, expiresIn);
        const settingTab = this.app.setting.activeTab;
        if (settingTab instanceof ObSyncSettingTab) {
          settingTab.display();
        }
      }
    });
    this.app.workspace.onLayoutReady(() => {
      if (this.settings.syncOnStartup) {
        this.syncEngine.runSync();
      }
      this.setupAutoSync();
    });
  }
  onunload() {
    if (this.autoSyncIntervalId !== null) {
      window.clearInterval(this.autoSyncIntervalId);
    }
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  setupAutoSync() {
    if (this.autoSyncIntervalId !== null) {
      window.clearInterval(this.autoSyncIntervalId);
      this.autoSyncIntervalId = null;
    }
    if (this.settings.autoSyncInterval > 0) {
      const ms = this.settings.autoSyncInterval * 60 * 1e3;
      this.autoSyncIntervalId = window.setInterval(() => {
        this.syncEngine.runSync();
      }, ms);
      this.registerInterval(this.autoSyncIntervalId);
    }
  }
};
